### ISSUE TITLE
Redshift connection string?

### ISSUE THREAD

**Issue by davoutuk** [tylerFowler/docker-superset#11]
Hello,

I've downloaded your superset docker container and I want to connect to an AWS Redshift database but can't get the 'test connection' to work.  

Can you please provide an example of how to configure this?

**Comment by tylerFowler** [comment]
Sure! So you're in luck because I've included the Postgres & Redshift drivers by default in the base Docker image so you don't need anything custom there (or at least not to connect to a Redshift DB).

So once you've got it installed you just need your Redshift connection string to look like so:
```
postgresql+psycopg2://{user}:{password}@example.url.us-west-2.redshift.amazonaws.com:5432/{database}
```

That should be enough to make it work, if you run into connection problems still (especially if it's a connection timeout) make sure your firewall rules in AWS are set up to accept connections from your Superset host.

**Comment by tylerFowler** [comment]
@davoutuk Closing this assuming this solved your problem, if you're still having issues though let me know and can troubleshoot a bit more.
